#spring.profiles.active=dev, test, custom
#spring.application.name=exmpleAlibou
#my.custom.property= Hello Hanagami
#my.custom.property.int= 123

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo_db
    username: hanagami
    password: hanagami
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect